
import { Voice } from './types';

export const VOICES: Voice[] = [
  { name: "Puck", gender: "Pria", id: "Puck" },
  { name: "Kore", gender: "Wanita", id: "Kore" },
  { name: "Zephyr", gender: "Wanita", id: "Zephyr" },
  { name: "Fenrir", gender: "Pria", id: "Fenrir" },
  { name: "Achird", gender: "Pria", id: "Achird"},
  { name: "Charon", gender: "Pria", id: "Charon" },
  { name: "Sadachbia", gender: "Pria", id: "Sadachbia" },
  { name: "Sulafat", gender: "Wanita", id: "Sulafat" },
  { name: "Aoede", gender: "Wanita", id: "Aoede" },
  { name: "Umbriel", gender: "Pria", id: "Umbriel" },
  { name: "Gacrux", gender: "Wanita", id: "Gacrux"},
  { name: "Leda", gender: "Wanita", id: "Leda" },
  { name: "Orus", gender: "Pria", id: "Orus" },
  { name: "Enceladus", gender: "Pria", id: "Enceladus" },
  { name: "Algenib", gender: "Pria", id: "Algenib" },
  { name: "Vindemiatrix", gender: "Wanita", id: "Vindemiatrix" },
  { name: "Sadaltager", gender: "Pria", id: "Sadaltager" },
  { name: "Schedar", gender: "Pria", id: "Schedar" },
  { name: "Iapetus", gender: "Pria", id: "Iapetus" },
];

export const ALL_POSES = [
    'Pose fashion dinamis dengan satu tangan di pinggul dan tangan lainnya diangkat ke atas',
    'Pose klasik dengan tangan di saku celana',
    'Menyender ke dinding dengan santai, satu kaki ditekuk',
    'Pose fashion dinamis membentuk huruf S dengan tubuh',
    'Berdiri tegak dengan tatapan kuat, tangan menyilang di dada',
    'Pose contrapposto, berat badan pada satu kaki, pinggul miring',
    'Berdiri dengan kaki terbuka lebar, pose yang kuat dan percaya diri',
    'Pose dari belakang (standing backpose), menoleh sedikit ke kamera',
    'Pose dari samping (side profile), menatap lurus ke depan',
    'Satu tangan di pinggul, tangan lain memegang kerah baju atau aksesori',
    'Pose asimetris, satu bahu lebih tinggi dari yang lain',
    'Pose minimalis, berdiri lurus menatap kamera dengan ekspresi netral',
    'Pose berjalan, seolah-olah tertangkap kamera sedang melangkah',
    'Pose melompat kecil dengan ekspresi ceria',
    'Pose berputar (spinning), dengan gaun atau rambut yang bergerak',
    'Pose berlari kecil dengan gaya candid',
    'Duduk di kursi dengan elegan, satu kaki menyilang di atas yang lain',
    'Duduk di lantai dengan santai, satu lutut ditekuk ke atas',
    'Duduk di tangga, menatap ke arah atas atau bawah',
    'Duduk di lantai dengan kaki lurus ke depan, menonjolkan sepatu',
    'Beauty shot close-up, fokus pada wajah dan riasan, dengan senyuman lembut',
    'Tangan membingkai wajah atau menyentuh rambut dengan lembut',
    'Pose half-body yang elegan, satu tangan diangkat ke dekat dagu',
    'Menatap tajam ke kamera dengan ekspresi serius (fierce)',
    'Tertawa lepas, candid close-up',
    'Satu tangan di bahu, tubuh sedikit miring ke samping',
    'Melihat ke belakang lewat bahu (over-the-shoulder)',
    'Pose dramatis dengan permainan bayangan yang kuat pada wajah atau tubuh',
    'Berinteraksi dengan properti (misal: memegang topi, kacamata, atau tas)',
    'Pose berbaring di lantai atau sofa dengan gaya high fashion',
];
